remove hacking checks from keystoneclient
the only hacking check in keystoneclient is related to
older versions of oslo libraries, which are no longer
supported by keystoneclient, for example:

$ pip freeze | grep oslo.utils
oslo.utils==3.18.0
$ python
>>> import oslo.utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named oslo.utils
>>> import oslo_utils
>>>

Let's just remove the hacking check since theres no
way someone could incorrectly import the older
versions.

Closes-Bug: 1652458

Signed-off-by: Adam Williamson <awilliam@redhat.com>

Change-Id: I14165903b46d2fc26e8c9de591917893f58516db